### ISSUE TITLE
pressing ESC does not call the function goFullscreen() while exiting

### ISSUE THREAD

**Issue by Rafi993** [fabiobiondi/angular-fullscreen#53]
Pressing ESC does not call goFullscreen() function when in fullscreen. But the function gets triggerd when the element is clicked. I wanted a small element to occupy fullscreen when clicked but It did not occupy the whole witdh and height of the screen so I used the function to set class. But since ESC is not triggered the set class does not get unset when ESC is pressed but it does when the button is pressed

**Comment by Rafi993** [comment]
even though the function was not tirggred it did find a workaround by always setting the height of the element that should go to fullscreen to 100% and placing it inside a div with restricted height.

**Comment by goors** [comment]
yes i can confirm goFullscreen is not called on esc. what  waste of time.

**Comment by Rafi993** [comment]
I managed to use trigger the method manualy when the events fire on esc is pressed as given [here](http://stackoverflow.com/questions/9621499/fullscreen-api-which-events-are-fired). I will give it as a pull request
